### ISSUE TITLE
data-index.yaml

### ISSUE THREAD

**Issue by gtsiamis** [biocom-uib/vpf-tools#6]
I am trying to implement vpf-class to a set of assemblies that contain sequences from viruses. I have been able to install the app but I have a couple of questions with respect to the data-index.yaml file.

In this file the path of several reference files is provided. Is that correct? I have been able to download the reference files from the Supplementary files of the vpf-class manuscript? Is that OK or I need to download the files from another link?

The final_list.hmms file has been downloaded from the link provided.

Your assistance is greatly appreciated.

Regards
George

**Comment by michoug** [comment]
Hi,
Not a dev but here is my data-index.yaml

```
classificationFiles:
  baltimore:
    modelClassesFile: ./data/2019_VPF_BaltTax_REclassification_new.tsv
    scoreSamplesFile: ./data/2019_Uvigs_scoresBaltTax.tsv
  family:
    modelClassesFile: ./data/2019_VPF_FamTax_REclassification_new.tsv
    scoreSamplesFile: ./data/2019_Uvigs_scoresFamTax.tsv
  genus:
    modelClassesFile: ./data/2019_VPF_GenTax_REclassification_new.tsv
    scoreSamplesFile: ./data/2019_Uvigs_scoresGenTax.tsv
  host_domain:
    modelClassesFile: ./data/2019_VPF_DomHost_REclassification_new.tsv
    scoreSamplesFile: ./data/2019_Uvigs_scoresDomHost.tsv
  host_family:
    modelClassesFile: ./data/2019_VPF_FamHost_REclassification_new.tsv
    scoreSamplesFile: ./data/2019_Uvigs_scoresFamHost.tsv
  host_genus:
    modelClassesFile: ./data/2019_VPF_GenHost_REclassification_new.tsv
    scoreSamplesFile: ./data/2019_Uvigs_scoresGenHost.tsv

vpfsFile: ./data/final_list.hmms
```
